# Generated by Django 3.2.15 on 2022-10-06 14:47

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='posts',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
